name: ${project.name}
main: ${project.groupId}.${project.artifactId}.${project.name}
version: ${project.version}
description: ${project.description}
softdepend: [Vault]

commands:
  menu:
    description: The base for all menu actions
    usage: /menu [create|edit|delete|list|open|script|reload|grab|copy] [parameters...]
    aliases: [m]
    permissions: cyom.commands.menu
  sudo:
    description: Allows you to execute a command as another player
    usage: /sudo [player] [command]
    permissions: cyom.commands.sudo

permissions:
  cyom.commands.menu:
    description: Allows use of all menu commands
    default: op
    children:
      cyom.commands.menu.create: true
      cyom.commands.menu.copy: true
      cyom.commands.menu.edit: true
      cyom.commands.menu.delete: true
      cyom.commands.menu.list: true
      cyom.commands.menu.open: true
      cyom.commands.menu.script: true
      cyom.commands.menu.reload: true
      cyom.commands.menu.grab: true
  cyom.commands.menu.create:
    description: Allows creating of new menus
    default: op
  cyom.commands.menu.copy:
    description: Allows copying of existing menus
    default: op
  cyom.commands.menu.edit:
    description: Allows editing of existing menus
    default: op
  cyom.commands.menu.delete:
    description: Allows removing of existing menus
    default: op
  cyom.commands.menu.list:
    description: Allows listing of all menus
    default: op
  cyom.commands.menu.open:
    description: Allows opening of menus for other players
    default: op
  cyom.commands.menu.script:
    description: Allows use of all menu script commands
    default: op
    children:
      cyom.commands.menu.script.append: true
      cyom.commands.menu.script.clear: true
      cyom.commands.menu.script.delete: true
      cyom.commands.menu.script.export: true
      cyom.commands.menu.script.hide: true
      cyom.commands.menu.script.import: true
      cyom.commands.menu.script.insert: true
      cyom.commands.menu.script.replace: true
      cyom.commands.menu.script.show: true
      cyom.commands.menu.script.title: true
  cyom.commands.menu.reload:
    description: Allows reloading of menus from disk
    default: op
  cyom.commands.menu.grab:
    description: Allows grabbing copies of items from a menu
    default: op
  cyom.commands.sudo:
    description: Allows use of the sudo command
    default: op
  cyom.commands.menu.script.append:
    description: Allows use of the menu script append command
    default: false
  cyom.commands.menu.script.clear:
    description: Allows use of the menu script clear command
    default: false
  cyom.commands.menu.script.delete:
    description: Allows use of the menu script delete command
    default: false
  cyom.commands.menu.script.export:
    description: Allows use of the menu script export command
    default: false
  cyom.commands.menu.script.hide:
    description: Allows use of the menu script hide command
    default: false
  cyom.commands.menu.script.import:
    description: Allows use of the menu script import command
    default: false
  cyom.commands.menu.script.insert:
    description: Allows use of the menu script insert command
    default: false
  cyom.commands.menu.script.replace:
    description: Allows use of the menu script replace command
    default: false
  cyom.commands.menu.script.show:
    description: Allows use of the menu script show command
    default: false
  cyom.commands.menu.script.title:
    description: Allows use of the menu script title command
    default: false
  cyom.slot.lock.all:
    description: Treats the entire player inventory as a locked menu
    default: false
    children:
      cyom.slot.lock.storage: true
      cyom.slot.lock.hotbar: true
  cyom.slot.lock.storage:
    description: Treats the top 3 rows of the player's inventory as a locked menu
    default: false
    children:
      cyom.slot.lock.toprow: true
      cyom.slot.lock.middlerow: true
      cyom.slot.lock.bottomrow: true
  cyom.slot.lock.toprow:
    description: Treats the top row of the player's inventory as a locked menu
    default: false
    children:
      cyom.slot.lock.9: true
      cyom.slot.lock.10: true
      cyom.slot.lock.11: true
      cyom.slot.lock.12: true
      cyom.slot.lock.13: true
      cyom.slot.lock.14: true
      cyom.slot.lock.15: true
      cyom.slot.lock.16: true
      cyom.slot.lock.17: true
  cyom.slot.lock.middlerow:
    description: Treats the middle row of the player's inventory as a locked menu
    default: false
    children:
      cyom.slot.lock.18: true
      cyom.slot.lock.19: true
      cyom.slot.lock.20: true
      cyom.slot.lock.21: true
      cyom.slot.lock.22: true
      cyom.slot.lock.23: true
      cyom.slot.lock.24: true
      cyom.slot.lock.25: true
      cyom.slot.lock.26: true
  cyom.slot.lock.bottomrow:
    description: Treats the bottom row of the player's inventory as a locked menu
    default: false
    children:
      cyom.slot.lock.27: true
      cyom.slot.lock.28: true
      cyom.slot.lock.29: true
      cyom.slot.lock.30: true
      cyom.slot.lock.31: true
      cyom.slot.lock.32: true
      cyom.slot.lock.33: true
      cyom.slot.lock.34: true
      cyom.slot.lock.35: true
  cyom.slot.lock.hotbar:
    description: Treats the player's hotbar as a locked menu
    default: false
    children:
      cyom.slot.lock.0: true
      cyom.slot.lock.1: true
      cyom.slot.lock.2: true
      cyom.slot.lock.3: true
      cyom.slot.lock.4: true
      cyom.slot.lock.5: true
      cyom.slot.lock.6: true
      cyom.slot.lock.7: true
      cyom.slot.lock.8: true
  i.have.every.permission:
    description: Displays a warning about slot locking to all server owners who recklessly grant players the '*' permission node
    default: false
